import PPButton from "components/ui/PPButton";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { trpc } from "utils/trpc";

const Home: NextPage = () => {
  const router = useRouter();
  const [roomId, setRoomId] = useState("");
  const createRoomMutation = trpc.room.createRoom.useMutation({
    onMutate: () => console.log("mutatin"),
    onError: (e) => console.error(e),
    onSuccess: (room) => router.push(`/room/${room.publicId}`),
  });
  const joinRoomMutation = trpc.room.joinRoom.useMutation();

  function handleCreateRoom() {
    createRoomMutation.mutate();
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col items-center justify-center bg-stone-700">
        <div className="container mx-auto flex flex-col items-center justify-center">
          <div className="flex flex-col items-center gap-8">
            <h1 className="text-4xl font-extrabold">
              Welcome to Planning Poker
            </h1>
            <PPButton onClick={handleCreateRoom}>Create room</PPButton>
            <div className="flex gap-2">
              <input
                value={roomId}
                onChange={(e) => setRoomId(e.target.value)}
                className="border border-black px-2 py-1"
              />
              <PPButton>Join room</PPButton>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
